import type {
  MenuItem,
  Testimonial,
  GalleryImage,
  RestaurantInfo,
  CategoryInfo,
} from './types';

export const restaurantInfo: RestaurantInfo = {
  name: 'CurryMama',
  tagline: 'Authentic Indian & Pakistani Cuisine',
  address: '30 Crumlin Rd, Crumlin',
  city: 'Dublin',
  state: 'Co. Dublin',
  zip: 'D12 HXW0',
  phone: '(01) 538 1281',
  email: 'Unxox11@gmail.com',
  hours: [
    { day: 'Monday', open: '12:00 PM', close: '10:00 PM' },
    { day: 'Tuesday', open: '12:00 PM', close: '10:00 PM' },
    { day: 'Wednesday', open: '12:00 PM', close: '10:00 PM' },
    { day: 'Thursday', open: '12:00 PM', close: '10:00 PM' },
    { day: 'Friday', open: '12:00 PM', close: '11:00 PM' },
    { day: 'Saturday', open: '12:00 PM', close: '11:00 PM' },
    { day: 'Sunday', open: '1:00 PM', close: '10:00 PM' },
  ],
  social: {
    facebook: 'https://facebook.com/CurryMama',
    instagram: 'https://instagram.com/CurryMama',
    twitter: 'https://twitter.com/CurryMama',
    youtube: 'https://youtube.com/CurryMama',
  },
  deliveryFee: 3.50,
  minOrder: 15.00,
  estimatedDeliveryTime: '30–45 min',
};

export const categories: CategoryInfo[] = [
  {
    id: 'starters',
    label: 'Starters',
    icon: 'Flame',
    description: 'Crispy, savory bites to begin your feast',
  },
  {
    id: 'main-courses',
    label: 'Main Courses',
    icon: 'CookingPot',
    description: 'Rich curries and hearty dishes from the heart',
  },
  {
    id: 'biryani-rice',
    label: 'Biryani & Rice',
    icon: 'Wheat',
    description: 'Aromatic basmati layered with spice and tender meat',
  },
  {
    id: 'breads',
    label: 'Breads',
    icon: 'Sandwich',
    description: 'Fresh from the tandoor, perfect for scooping curry',
  },
  {
    id: 'desserts',
    label: 'Desserts',
    icon: 'CakeSlice',
    description: 'Sweet traditional endings to your meal',
  },
  {
    id: 'drinks',
    label: 'Drinks',
    icon: 'CupSoda',
    description: 'Cooling lassis, chai, and refreshing beverages',
  },
];

export const menuItems: MenuItem[] = [
  // Starters
  {
    id: 'sam-01',
    name: 'Vegetable Samosa (2 pcs)',
    description:
      'Crispy golden pastry stuffed with spiced potatoes, peas, and aromatic herbs. Served with tamarind chutney.',
    price: 5.99,
    category: 'starters',
    image:
      'https://images.pexels.com/photos/8992923/pexels-photo-8992923.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isFeatured: true,
    isBestseller: true,
    isNew: false,
    allergens: ['gluten'],
    prepTime: '10 min',
    calories: 280,
    rating: 4.8,
    reviewCount: 342,
  },
  {
    id: 'pak-01',
    name: 'Paneer Pakora',
    description:
      'Cubes of cottage cheese marinated in spiced gram flour batter, deep-fried to golden perfection. Served with mint chutney.',
    price: 7.49,
    category: 'starters',
    image:
      'https://images.pexels.com/photos/8585763/pexels-photo-8585763.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'medium',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    allergens: ['dairy'],
    prepTime: '12 min',
    calories: 320,
    rating: 4.6,
    reviewCount: 189,
  },
  {
    id: 'tik-01',
    name: 'Chicken Tikka',
    description:
      'Tender chicken pieces marinated in yogurt and spices, char-grilled in the tandoor. Served with onion rings and chutney.',
    price: 9.99,
    category: 'starters',
    image:
      'https://images.pexels.com/photos/6522616/pexels-photo-6522616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'medium',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: true,
    isBestseller: true,
    isNew: false,
    allergens: ['dairy'],
    prepTime: '15 min',
    calories: 340,
    rating: 4.9,
    reviewCount: 421,
  },
  {
    id: 'see-01',
    name: 'Seekh Kebab',
    description:
      'Minced lamb skewers blended with onions, green chilies, and garam masala. Grilled over open flame for smoky flavor.',
    price: 10.99,
    category: 'starters',
    image:
      'https://images.pexels.com/photos/9646858/pexels-photo-9646858.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'hot',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: false,
    isBestseller: false,
    isNew: true,
    allergens: [],
    prepTime: '18 min',
    calories: 380,
    rating: 4.7,
    reviewCount: 156,
  },
  // Main Courses
  {
    id: 'but-01',
    name: 'Butter Chicken',
    description:
      'Tandoori chicken simmered in a velvety tomato-cream gravy with butter, fenugreek, and a hint of cardamom. Our most-loved dish.',
    price: 16.99,
    category: 'main-courses',
    image:
      'https://images.pexels.com/photos/12737809/pexels-photo-12737809.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: true,
    isBestseller: true,
    isNew: false,
    allergens: ['dairy'],
    prepTime: '20 min',
    calories: 520,
    rating: 4.9,
    reviewCount: 892,
  },
  {
    id: 'pal-01',
    name: 'Palak Paneer',
    description:
      'Soft paneer cubes in a creamy spinach gravy tempered with cumin, garlic, and garam masala. A classic vegetarian favorite.',
    price: 14.99,
    category: 'main-courses',
    image:
      'https://images.pexels.com/photos/31249589/pexels-photo-31249589.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: true,
    isBestseller: true,
    isNew: false,
    allergens: ['dairy'],
    prepTime: '18 min',
    calories: 410,
    rating: 4.8,
    reviewCount: 567,
  },
  {
    id: 'dal-01',
    name: 'Dal Makhani',
    description:
      'Black lentils slow-cooked overnight with butter, cream, and tomatoes. Rich, smoky, and deeply satisfying.',
    price: 13.99,
    category: 'main-courses',
    image:
      'https://images.pexels.com/photos/37182513/pexels-photo-37182513.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: false,
    isBestseller: true,
    isNew: false,
    allergens: ['dairy'],
    prepTime: '25 min',
    calories: 380,
    rating: 4.7,
    reviewCount: 334,
  },
  {
    id: 'rog-01',
    name: 'Lamb Rogan Josh',
    description:
      'Tender lamb braised in a fiery Kashmiri chili gravy with aromatic spices. A signature dish from the valleys of Kashmir.',
    price: 18.99,
    category: 'main-courses',
    image:
      'https://images.pexels.com/photos/30203309/pexels-photo-30203309.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'hot',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    allergens: [],
    prepTime: '30 min',
    calories: 560,
    rating: 4.8,
    reviewCount: 298,
  },
  {
    id: 'kar-01',
    name: 'Chicken Karahi',
    description:
      'Wok-tossed chicken with tomatoes, ginger, green chilies, and fresh cilantro. A Pakistani street-food classic.',
    price: 15.99,
    category: 'main-courses',
    image:
      'https://images.pexels.com/photos/29684985/pexels-photo-29684985.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'hot',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: true,
    isBestseller: false,
    isNew: false,
    allergens: [],
    prepTime: '22 min',
    calories: 480,
    rating: 4.7,
    reviewCount: 234,
  },
  {
    id: 'pnm-01',
    name: 'Paneer Butter Masala',
    description:
      'Paneer cubes in a luscious tomato-cashew gravy with butter and cream. Mild, creamy, and crowd-pleasing.',
    price: 14.49,
    category: 'main-courses',
    image:
      'https://images.pexels.com/photos/11188417/pexels-photo-11188417.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    allergens: ['dairy', 'nuts'],
    prepTime: '18 min',
    calories: 450,
    rating: 4.6,
    reviewCount: 201,
  },
  // Biryani & Rice
  {
    id: 'bir-01',
    name: 'Chicken Biryani',
    description:
      'Basmati rice layered with marinated chicken, saffron, fried onions, and mint. Dum-cooked and served with raita.',
    price: 15.99,
    category: 'biryani-rice',
    image:
      'https://images.pexels.com/photos/9609869/pexels-photo-9609869.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'medium',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: true,
    isBestseller: true,
    isNew: false,
    allergens: ['dairy'],
    prepTime: '25 min',
    calories: 620,
    rating: 4.9,
    reviewCount: 743,
  },
  {
    id: 'bir-02',
    name: 'Lamb Biryani',
    description:
      'Slow-cooked lamb layered with fragrant basmati, whole spices, and caramelized onions. A feast in every bite.',
    price: 17.99,
    category: 'biryani-rice',
    image:
      'https://images.pexels.com/photos/17696654/pexels-photo-17696654.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'medium',
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    allergens: ['dairy'],
    prepTime: '30 min',
    calories: 680,
    rating: 4.8,
    reviewCount: 312,
  },
  {
    id: 'bir-03',
    name: 'Vegetable Biryani',
    description:
      'Basmati rice with garden vegetables, cashews, raisins, and biryani spices. Dum-cooked to fluffy perfection.',
    price: 12.99,
    category: 'biryani-rice',
    image:
      'https://images.pexels.com/photos/28909536/pexels-photo-28909536.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    allergens: ['nuts'],
    prepTime: '22 min',
    calories: 480,
    rating: 4.6,
    reviewCount: 178,
  },
  {
    id: 'ric-01',
    name: 'Jeera Rice',
    description:
      'Fluffy basmati rice tempered with cumin seeds and ghee. The perfect companion to any curry.',
    price: 4.99,
    category: 'biryani-rice',
    image:
      'https://images.pexels.com/photos/28674713/pexels-photo-28674713.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    allergens: ['dairy'],
    prepTime: '12 min',
    calories: 240,
    rating: 4.5,
    reviewCount: 142,
  },
  // Breads
  {
    id: 'naa-01',
    name: 'Garlic Naan',
    description:
      'Soft tandoor-baked flatbread brushed with garlic butter and fresh cilantro. Irresistibly fragrant.',
    price: 3.49,
    category: 'breads',
    image:
      'https://images.pexels.com/photos/10337726/pexels-photo-10337726.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isFeatured: true,
    isBestseller: true,
    isNew: false,
    allergens: ['gluten', 'dairy'],
    prepTime: '8 min',
    calories: 260,
    rating: 4.9,
    reviewCount: 523,
  },
  {
    id: 'naa-02',
    name: 'Butter Naan',
    description:
      'Classic tandoor naan brushed with melted butter. Pillowy soft and perfect for mopping up curry.',
    price: 2.99,
    category: 'breads',
    image:
      'https://images.pexels.com/photos/6183640/pexels-photo-6183640.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    allergens: ['gluten', 'dairy'],
    prepTime: '8 min',
    calories: 240,
    rating: 4.7,
    reviewCount: 298,
  },
  {
    id: 'rot-01',
    name: 'Tandoori Roti',
    description:
      'Whole-wheat flatbread baked in the tandoor. A lighter alternative to naan.',
    price: 2.49,
    category: 'breads',
    image:
      'https://images.pexels.com/photos/28674556/pexels-photo-28674556.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    allergens: ['gluten'],
    prepTime: '6 min',
    calories: 160,
    rating: 4.5,
    reviewCount: 167,
  },
  {
    id: 'lac-01',
    name: 'Lachha Paratha',
    description:
      'Flaky, multi-layered whole-wheat flatbread. Crispy on the outside, soft within.',
    price: 3.49,
    category: 'breads',
    image:
      'https://images.pexels.com/photos/20446390/pexels-photo-20446390.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    isFeatured: false,
    isBestseller: false,
    isNew: true,
    allergens: ['gluten'],
    prepTime: '8 min',
    calories: 220,
    rating: 4.6,
    reviewCount: 112,
  },
  // Desserts
  {
    id: 'gul-01',
    name: 'Gulab Jamun (2 pcs)',
    description:
      'Deep-fried milk-solid dumplings soaked in warm rose-cardamom syrup. Served with a drizzle of cream.',
    price: 5.99,
    category: 'desserts',
    image:
      'https://images.pexels.com/photos/9198596/pexels-photo-9198596.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    isFeatured: true,
    isBestseller: true,
    isNew: false,
    allergens: ['dairy'],
    prepTime: '5 min',
    calories: 320,
    rating: 4.9,
    reviewCount: 387,
  },
  {
    id: 'khe-01',
    name: 'Kheer',
    description:
      'Creamy rice pudding simmered with milk, cardamom, saffron, and a garnish of pistachios and almonds.',
    price: 4.99,
    category: 'desserts',
    image:
      'https://images.pexels.com/photos/31109623/pexels-photo-31109623.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    allergens: ['dairy', 'nuts'],
    prepTime: '5 min',
    calories: 280,
    rating: 4.7,
    reviewCount: 203,
  },
  // Drinks
  {
    id: 'las-01',
    name: 'Mango Lassi',
    description:
      'Thick, creamy yogurt blended with sweet Alphonso mango and a touch of cardamom. Refreshing and cooling.',
    price: 4.49,
    category: 'drinks',
    image:
      'https://images.pexels.com/photos/14509267/pexels-photo-14509267.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: true,
    isBestseller: true,
    isNew: false,
    allergens: ['dairy'],
    prepTime: '3 min',
    calories: 190,
    rating: 4.8,
    reviewCount: 256,
  },
  {
    id: 'cha-01',
    name: 'Masala Chai',
    description:
      'Black tea simmered with milk, cardamom, ginger, cinnamon, and cloves. A warm, spiced hug in a cup.',
    price: 2.99,
    category: 'drinks',
    image:
      'https://images.pexels.com/photos/37186989/pexels-photo-37186989.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    spiceLevel: 'mild',
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    allergens: ['dairy'],
    prepTime: '5 min',
    calories: 120,
    rating: 4.7,
    reviewCount: 189,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Priya Sharma',
    role: 'Food Blogger',
    avatar: 'https://i.pravatar.cc/150?img=44',
    rating: 5,
    text: 'The butter chicken here is the best I have had outside of Delhi. The flavors are authentic, the portions generous, and the naan is always fresh from the tandoor. CurryMama has become my go-to for Indian food in the city.',
    date: '2025-08-15',
  },
  {
    id: 't2',
    name: 'Imran Khan',
    role: 'Regular Customer',
    avatar: 'https://i.pravatar.cc/150?img=12',
    rating: 5,
    text: 'Their chicken karahi takes me right back to the streets of Lahore. The spice level is perfect, and you can taste the quality of every ingredient. The delivery is always fast and the food arrives hot.',
    date: '2025-07-22',
  },
  {
    id: 't3',
    name: 'Sarah Johnson',
    role: 'Local Foodie',
    avatar: 'https://i.pravatar.cc/150?img=47',
    rating: 5,
    text: 'I ordered the lamb biryani for a family dinner and everyone was blown away. The rice was fluffy, the lamb was tender, and the spices were perfectly balanced. The gulab jamun for dessert was the cherry on top.',
    date: '2025-09-01',
  },
  {
    id: 't4',
    name: 'Raj Patel',
    role: 'Verified Customer',
    avatar: 'https://i.pravatar.cc/150?img=33',
    rating: 4,
    text: 'The palak paneer is creamy and comforting, exactly like my mom makes. The only thing I wish is that they had more vegan options. But the vegetable biryani is excellent and the mango lassi is to die for.',
    date: '2025-08-30',
  },
  {
    id: 't5',
    name: 'Emily Chen',
    role: 'First-Time Visitor',
    avatar: 'https://i.pravatar.cc/150?img=20',
    rating: 5,
    text: 'I am new to Indian food and the staff was incredibly helpful in guiding me through the menu. The samosas were a great starter, and the dal makhani was so rich and flavorful. I will definitely be coming back.',
    date: '2025-09-05',
  },
  {
    id: 't6',
    name: 'Amit Verma',
    role: 'Food Critic',
    avatar: 'https://i.pravatar.cc/150?img=68',
    rating: 5,
    text: 'CurryMama delivers a genuine taste of the subcontinent. The rogan josh is deeply spiced without being overwhelming, and the seekh kebabs are smoky and tender. This is serious cooking, not dumbed down for anyone.',
    date: '2025-08-18',
  },
];

export const galleryImages: GalleryImage[] = [
  {
    id: 'g1',
    src: 'https://images.pexels.com/photos/38349089/pexels-photo-38349089.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Restaurant interior with warm lighting',
    caption: 'Our warm, inviting dining room',
  },
  {
    id: 'g2',
    src: 'https://images.pexels.com/photos/35539324/pexels-photo-35539324.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Traditional Indian thali platter',
    caption: 'A traditional thali feast',
  },
  {
    id: 'g3',
    src: 'https://images.pexels.com/photos/39059254/pexels-photo-39059254.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Grilled chicken skewers',
    caption: 'Smoky tandoor-grilled kebabs',
  },
  {
    id: 'g4',
    src: 'https://images.pexels.com/photos/29850004/pexels-photo-29850004.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Spread of Indian dishes',
    caption: 'A spread for the whole table',
  },
  {
    id: 'g5',
    src: 'https://images.pexels.com/photos/31280796/pexels-photo-31280796.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Colorful spices in bowls',
    caption: 'The spices that make everything sing',
  },
  {
    id: 'g6',
    src: 'https://images.pexels.com/photos/19447626/pexels-photo-19447626.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Cozy restaurant ambiance',
    caption: 'Dine in comfort and style',
  },
  {
    id: 'g7',
    src: 'https://images.pexels.com/photos/8818732/pexels-photo-8818732.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Festive Indian food spread',
    caption: 'Perfect for celebrations',
  },
  {
    id: 'g8',
    src: 'https://images.pexels.com/photos/7208238/pexels-photo-7208238.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    alt: 'Spice powders in metal bowls',
    caption: 'Freshly ground every morning',
  },
];
